ENV: LOCAL
CONFIG_COINBASE_RECEIVING_ADDRESS: 19znD4R6CTKpuXdhTPw2upnQpuHrGyzn2K
CONFIG_SEED_NODES:
- "127.0.0.1:34212"
CONFIG_VERSION: 32

DHT_NODE_EXPIRED_AFTER: ""
DHT_BUCKET_EXPIRED_AFTER: ""
DHT_CHECK_BUCKET_PERIOD: "5s"
DHT_MAX_TRANSACTION_CURSOR: 4294967295
DHT_MAX_NODE: 5000
DHT_K: 8
DHT_BUCKET_SIZE: 2147483647
DHT_REFRESH_NODE_COUNT: "256"
DHT_NETWORK: "udp4"
DHT_LOCAL_ADDR: ":34212"